/*
 * Automatically generated by jrpcgen 1.0.7 on 12/19/23, 5:46 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "acs" ONC/RPC program.
 */
public interface acs {
    public static final int list_1 = 4;
    public static final int FTP = 0x24345678;
    public static final int delete_1 = 3;
    public static final int write_1 = 2;
    public static final int read_file_1 = 1;
    public static final int V1 = 1;
}
// End of acs.java
