/*
 * Automatically generated by jrpcgen 1.0.7 on 12/19/23, 5:46 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class response implements XdrAble {
    public int code;
    public String body;

    public response() {
    }

    public response(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(code);
        xdr.xdrEncodeString(body);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        code = xdr.xdrDecodeInt();
        body = xdr.xdrDecodeString();
    }

}
// End of response.java
